// ============================================================
// scripts/seedProducts.js - TẠO NHIỀU SẢN PHẨM MẪU
// ============================================================
// Chạy: node scripts/seedProducts.js

require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../src/models/Product");

const products = [
  // TRÁI CÂY (15 sản phẩm)
  {
    id: "TC001",
    name: "Ổi trân châu ruột đỏ (1kg)",
    category: "trái cây",
    price: 31000,
    discount: 0.4,
    rating: "4/5",
    stock: 100,
    unit: "kg",
    image: "/img/poster_oi.jpg",
    images: ["/img/oi1.jpg", "/img/oi2.jpg", "/img/oi3.jpg"],
    description:
      "Ổi trân châu ruột đỏ giòn ngọt, tươi ngon, trái to, không bị dập.",
    descriptionDetail:
      "Ổi trân châu ruột đỏ từ vùng đất Tiền Giang. Giòn ngọt tự nhiên, ruột đỏ hồng bắt mắt, giàu vitamin C và chất xơ. Cam kết 100% an toàn vệ sinh thực phẩm.",
    origin: "Tiền Giang",
    certifications: ["VietGAP", "OCOP 4 sao"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC002",
    name: "Xoài keo (2-3 trái)",
    category: "trái cây",
    price: 25000,
    discount: 0.2,
    rating: "4.5/5",
    stock: 150,
    unit: "kg",
    image: "/img/poster_xoai.jpg",
    images: ["/img/xoai1.jpg", "/img/xoai2.jpg", "/img/xoai3.jpg"],
    description: "Xoài keo chất lượng, tươi ngon, trái to, sống, căng trái.",
    descriptionDetail:
      "Xoài keo đặc sản Đồng Tháp, vị ngọt đậm đà, thơm mùi đặc trưng. Trái to đều, múi dày, hạt mỏng.",
    origin: "Đồng Tháp",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC003",
    name: "Dưa hấu đỏ (1.8kg)",
    category: "trái cây",
    price: 38000,
    discount: 0.1,
    rating: "5/5",
    stock: 80,
    unit: "trái",
    image: "/img/poster_duahau.jpg",
    images: ["/img/duahau1.jpg", "/img/duahau2.jpg"],
    description: "Dưa hấu đỏ ngọt, nhiều nước, giải khát tốt trong mùa nóng.",
    descriptionDetail:
      "Dưa hấu Long An ngọt mát tự nhiên, ruột đỏ tươi, độ ngọt 12-13 Brix. Hoàn hảo cho những ngày hè nóng bức.",
    origin: "Long An",
    inStock: true,
    featured: false,
  },
  {
    id: "TC004",
    name: "Chuối già Nam Mỹ (1kg)",
    category: "trái cây",
    price: 33000,
    discount: 0.2,
    rating: "3.5/5",
    stock: 120,
    unit: "kg",
    image: "/img/poster_chuoi.jpg",
    images: ["/img/chuoi1.jpg", "/img/chuoi2.jpg"],
    description:
      "Chuối già chứa nhiều chất dinh dưỡng như kali, chất xơ, vitamin.",
    descriptionDetail:
      "Chuối già Nam Mỹ Bình Phước, giàu kali và vitamin B6, tốt cho tim mạch. Quả chín vàng đều, thịt dẻo ngọt.",
    origin: "Bình Phước",
    inStock: true,
    featured: false,
  },
  {
    id: "TC005",
    name: "Cam sành túi (1kg)",
    category: "trái cây",
    price: 25000,
    discount: 0.2,
    rating: "4/5",
    stock: 90,
    unit: "kg",
    image: "/img/poster_cam.jpg",
    images: ["/img/cam1.jpg", "/img/cam2.jpg"],
    description: "Cam sành ngọt thanh, giàu vitamin C.",
    descriptionDetail:
      "Cam sành Hà Giang múi mọng nước, vị ngọt thanh mát, vitamin C cao. Vỏ mỏng dễ bóc, ít hạt.",
    origin: "Hà Giang",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC006",
    name: "Bưởi da xanh Bến Tre (1 trái)",
    category: "trái cây",
    price: 45000,
    discount: 0.15,
    rating: "4.5/5",
    stock: 60,
    unit: "trái",
    image: "/img/poster_buoi.jpg",
    images: ["/img/buoi1.jpg", "/img/buoi2.jpg"],
    description: "Bưởi da xanh Bến Tre đặc sản nổi tiếng, múi mọng nước.",
    descriptionDetail:
      "Bưởi da xanh Bến Tre là đặc sản trứ danh, múi bưởi hồng đào, vị ngọt thanh, ít hạt. Cây trồng theo tiêu chuẩn VietGAP.",
    origin: "Bến Tre",
    certifications: ["VietGAP", "OCOP 5 sao"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC007",
    name: "Thanh long ruột đỏ (1kg)",
    category: "trái cây",
    price: 22000,
    discount: 0.1,
    rating: "4/5",
    stock: 110,
    unit: "kg",
    image: "/img/poster_thanhlong.jpg",
    images: ["/img/thanhlong1.jpg", "/img/thanhlong2.jpg"],
    description: "Thanh long ruột đỏ Bình Thuận, vị ngọt mát.",
    descriptionDetail:
      "Thanh long ruột đỏ Bình Thuận trái to đều, ruột đỏ tươi, ngọt tự nhiên 14-15 Brix. Giàu chất chống oxi hóa.",
    origin: "Bình Thuận",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "TC008",
    name: "Dứa Cayenne (1 trái)",
    category: "trái cây",
    price: 28000,
    discount: 0,
    rating: "4.5/5",
    stock: 70,
    unit: "trái",
    image: "/img/poster_dua.jpg",
    images: ["/img/dua1.jpg", "/img/dua2.jpg"],
    description: "Dứa Cayenne ngọt dịu, thơm đặc trưng.",
    descriptionDetail:
      "Dứa Cayenne Lâm Đồng ngọt thanh, thơm nức mùi, thịt vàng sáng. Thích hợp ăn tươi hoặc làm sinh tố.",
    origin: "Lâm Đồng",
    inStock: true,
    featured: false,
  },
  {
    id: "TC009",
    name: "Chôm chôm Thái (1kg)",
    category: "trái cây",
    price: 35000,
    discount: 0.2,
    rating: "4/5",
    stock: 85,
    unit: "kg",
    image: "/img/poster_chomchom.jpg",
    images: ["/img/chomchom1.jpg", "/img/chomchom2.jpg"],
    description: "Chôm chôm Thái ngọt, thơm, múi dày.",
    descriptionDetail:
      "Chôm chôm Thái Bến Tre trái to đều, múi dày mọng nước, ngọt mát tự nhiên. Dễ tách hạt.",
    origin: "Bến Tre",
    inStock: true,
    featured: false,
  },
  {
    id: "TC010",
    name: "Mít Thái siêu sớm (1 múi)",
    category: "trái cây",
    price: 42000,
    discount: 0.15,
    rating: "5/5",
    stock: 50,
    unit: "múi",
    image: "/img/poster_mit.jpg",
    images: ["/img/mit1.jpg", "/img/mit2.jpg"],
    description: "Mít Thái siêu sớm thịt dày, vị ngọt đậm.",
    descriptionDetail:
      "Mít Thái siêu sớm Tiền Giang múi dày mọng, vị ngọt béo đặc trưng, thơm nức mùi. Hạt nhỏ, múi to.",
    origin: "Tiền Giang",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC011",
    name: "Táo Envy New Zealand (4 trái)",
    category: "trái cây",
    price: 95000,
    discount: 0.1,
    rating: "5/5",
    stock: 40,
    unit: "hộp",
    image: "/img/poster_tao.jpg",
    images: ["/img/tao1.jpg", "/img/tao2.jpg"],
    description: "Táo Envy New Zealand giòn ngọt cao cấp.",
    descriptionDetail:
      "Táo Envy New Zealand nhập khẩu, giòn tan, ngọt thanh mát, vị cân bằng hoàn hảo. Đóng gói cao cấp.",
    origin: "New Zealand",
    inStock: true,
    featured: true,
  },
  {
    id: "TC012",
    name: "Nho đen không hạt Úc (500g)",
    category: "trái cây",
    price: 78000,
    discount: 0.05,
    rating: "5/5",
    stock: 35,
    unit: "kg",
    image: "/img/poster_nho.jpg",
    images: ["/img/nho1.jpg", "/img/nho2.jpg"],
    description: "Nho đen không hạt Úc ngọt mát cao cấp.",
    descriptionDetail:
      "Nho đen không hạt nhập khẩu từ Úc, quả to căng mọng, vỏ mỏng, ngọt tự nhiên 18 Brix.",
    origin: "Úc",
    inStock: true,
    featured: true,
  },
  {
    id: "TC013",
    name: "Lê Nam Phi (4 trái)",
    category: "trái cây",
    price: 62000,
    discount: 0,
    rating: "4.5/5",
    stock: 45,
    unit: "hộp",
    image: "/img/poster_le.jpg",
    images: ["/img/le1.jpg", "/img/le2.jpg"],
    description: "Lê Nam Phi giòn ngọt mát.",
    descriptionDetail:
      "Lê Nam Phi giòn tan, ngọt mát, nhiều nước. Thích hợp ăn tươi giải nhiệt.",
    origin: "Nam Phi",
    inStock: true,
    featured: false,
  },
  {
    id: "TC014",
    name: "Bơ 034 Đắk Lắk (3 trái)",
    category: "trái cây",
    price: 55000,
    discount: 0.2,
    rating: "4.5/5",
    stock: 65,
    unit: "kg",
    image: "/img/poster_bo.jpg",
    images: ["/img/bo1.jpg", "/img/bo2.jpg"],
    description: "Bơ 034 Đắk Lắk béo ngậy thơm ngon.",
    descriptionDetail:
      "Bơ 034 Đắk Lắk hạt nhỏ, thịt dày béo ngậy, màu vàng đẹp. Giàu chất béo lành mạnh.",
    origin: "Đắk Lắk",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "TC015",
    name: "Sầu riêng Ri6 Đồng Nai (1kg)",
    category: "trái cây",
    price: 125000,
    discount: 0.1,
    rating: "5/5",
    stock: 30,
    unit: "kg",
    image: "/img/poster_saurieng.jpg",
    images: ["/img/saurieng1.jpg", "/img/saurieng2.jpg"],
    description: "Sầu riêng Ri6 Đồng Nai thơm béo đặc trưng.",
    descriptionDetail:
      "Sầu riêng Ri6 Đồng Nai múi dày, màu vàng đậm, béo ngậy thơm nức. Độ khô 30-33%.",
    origin: "Đồng Nai",
    certifications: ["VietGAP", "OCOP 4 sao"],
    inStock: true,
    featured: true,
  },

  // RAU LÁ (12 sản phẩm)
  {
    id: "RL001",
    name: "Rau muống (500g)",
    category: "rau lá",
    price: 14000,
    discount: 0.2,
    rating: "4.5/5",
    stock: 200,
    unit: "bó",
    image: "/img/poster_raumuong.jpg",
    images: ["/img/raumuong1.jpg", "/img/raumuong2.jpg"],
    description: "Rau muống tươi, sạch, giàu vitamin A, C và sắt.",
    descriptionDetail:
      "Rau muống Đồng Tháp tươi non, lá xanh mướt, không dùng thuốc trừ sâu. Giàu chất xơ và vitamin.",
    origin: "Đồng Tháp",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "RL002",
    name: "Cải ngọt (500g)",
    category: "rau lá",
    price: 15000,
    discount: 0.3,
    rating: "4/5",
    stock: 180,
    unit: "bó",
    image: "/img/poster_caingot.jpg",
    images: ["/img/caingot1.jpg", "/img/caingot2.jpg"],
    description: "Cải ngọt vị ngọt thanh, phù hợp nhiều món ăn.",
    descriptionDetail:
      "Cải ngọt Lâm Đồng lá non mềm, vị ngọt tự nhiên. Trồng theo tiêu chuẩn VietGAP.",
    origin: "Lâm Đồng",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "RL003",
    name: "Mồng tơi (500g)",
    category: "rau lá",
    price: 15000,
    discount: 0.3,
    rating: "5/5",
    stock: 150,
    unit: "bó",
    image: "/img/poster_mongtoi.jpg",
    images: ["/img/mongtoi1.jpg", "/img/mongtoi2.jpg"],
    description: "Rau mồng tơi giàu vitamin và khoáng chất.",
    descriptionDetail:
      "Mồng tơi tươi non, lá xanh mướt, giàu canxi và sắt. Tốt cho sức khỏe xương khớp.",
    origin: "Đồng Tháp",
    inStock: true,
    featured: false,
  },
  {
    id: "RL004",
    name: "Xà lách lô lô (500g)",
    category: "rau lá",
    price: 16000,
    discount: 0.2,
    rating: "4/5",
    stock: 160,
    unit: "bó",
    image: "/img/poster_xalach.jpg",
    images: ["/img/xalach1.jpg", "/img/xalach2.jpg"],
    description: "Xà lách lô lô tươi, giòn, giàu vitamin.",
    descriptionDetail:
      "Xà lách lô lô Đà Lạt giòn ngọt, ít sâu bệnh. Hoàn hảo cho salad và món cuốn.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "RL005",
    name: "Hành lá (100g)",
    category: "rau lá",
    price: 7000,
    discount: 0.05,
    rating: "4/5",
    stock: 250,
    unit: "bó",
    image: "/img/poster_hanhla.jpg",
    images: ["/img/hanhla1.jpg", "/img/hanhla2.jpg"],
    description: "Hành lá tươi, thơm, bổ dưỡng.",
    descriptionDetail:
      "Hành lá Đồng Tháp tươi non, thơm đặc trưng. Giàu vitamin K và chất chống oxi hóa.",
    origin: "Đồng Tháp",
    inStock: true,
    featured: false,
  },
  {
    id: "RL006",
    name: "Rau cải thảo (1 bắp)",
    category: "rau lá",
    price: 18000,
    discount: 0.15,
    rating: "4/5",
    stock: 130,
    unit: "bắp",
    image: "/img/poster_caithao.jpg",
    images: ["/img/caithao1.jpg", "/img/caithao2.jpg"],
    description: "Cải thảo Đà Lạt tươi ngon, lá giòn ngọt.",
    descriptionDetail:
      "Cải thảo Đà Lạt bắp chắc, lá xanh mướt, vị ngọt thanh. Phù hợp nấu lẩu hoặc xào.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "RL007",
    name: "Rau dền đỏ (500g)",
    category: "rau lá",
    price: 13000,
    discount: 0.2,
    rating: "4.5/5",
    stock: 170,
    unit: "bó",
    image: "/img/poster_rauden.jpg",
    images: ["/img/rauden1.jpg", "/img/rauden2.jpg"],
    description: "Rau dền đỏ giàu sắt, tốt cho máu.",
    descriptionDetail:
      "Rau dền đỏ tươi non, giàu sắt và vitamin A. Giúp bổ máu hiệu quả.",
    origin: "Đồng Tháp",
    inStock: true,
    featured: false,
  },
  {
    id: "RL008",
    name: "Cải bó xôi baby (300g)",
    category: "rau lá",
    price: 22000,
    discount: 0.1,
    rating: "5/5",
    stock: 90,
    unit: "gói",
    image: "/img/poster_caiboxoi.jpg",
    images: ["/img/caiboxoi1.jpg", "/img/caiboxoi2.jpg"],
    description: "Cải bó xôi baby tươi, giàu sắt và folate.",
    descriptionDetail:
      "Cải bó xôi baby Đà Lạt lá non mềm, giàu sắt, folate và chất xơ. Tốt cho sức khỏe tim mạch.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "RL009",
    name: "Cải kale xoăn (300g)",
    category: "rau lá",
    price: 28000,
    discount: 0,
    rating: "4.5/5",
    stock: 75,
    unit: "gói",
    image: "/img/poster_kale.jpg",
    images: ["/img/kale1.jpg", "/img/kale2.jpg"],
    description: "Cải kale xoăn - siêu thực phẩm giàu dinh dưỡng.",
    descriptionDetail:
      "Cải kale xoăn Đà Lạt giàu vitamin K, C, chất chống oxi hóa. Thích hợp làm salad hoặc sinh tố.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "RL010",
    name: "Rau tần ô (500g)",
    category: "rau lá",
    price: 19000,
    discount: 0.15,
    rating: "4/5",
    stock: 120,
    unit: "bó",
    image: "/img/poster_tauno.jpg",
    images: ["/img/tauno1.jpg", "/img/tauno2.jpg"],
    description: "Rau tần ô thơm ngọt, giàu vitamin.",
    descriptionDetail:
      "Rau tần ô Đà Lạt có mùi thơm đặc trưng, giàu vitamin A và C. Tốt cho thị lực.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "RL011",
    name: "Rau ngót (500g)",
    category: "rau lá",
    price: 14000,
    discount: 0.2,
    rating: "4/5",
    stock: 140,
    unit: "bó",
    image: "/img/poster_raungot.jpg",
    images: ["/img/raungot1.jpg", "/img/raungot2.jpg"],
    description: "Rau ngót tươi, giúp giải nhiệt mát gan.",
    descriptionDetail:
      "Rau ngót Đồng Tháp lá non mềm, vị ngọt thanh. Có tác dụng mát gan, giải độc.",
    origin: "Đồng Tháp",
    inStock: true,
    featured: false,
  },
  {
    id: "RL012",
    name: "Rau má (500g)",
    category: "rau lá",
    price: 17000,
    discount: 0.1,
    rating: "4.5/5",
    stock: 110,
    unit: "bó",
    image: "/img/poster_rauma.jpg",
    images: ["/img/rauma1.jpg", "/img/rauma2.jpg"],
    description: "Rau má tươi, giúp thanh nhiệt giải độc.",
    descriptionDetail:
      "Rau má tươi sạch, giàu chất chống oxi hóa. Tốt cho da và hệ thần kinh.",
    origin: "Đồng Tháp",
    inStock: true,
    featured: false,
  },

  // CỦ QUẢ (10 sản phẩm)
  {
    id: "CQ001",
    name: "Cà rốt (500g)",
    category: "củ quả",
    price: 10000,
    discount: 0,
    rating: "3/5",
    stock: 200,
    unit: "kg",
    image: "/img/poster_carot.jpg",
    images: ["/img/carot1.jpg", "/img/carot2.jpg"],
    description: "Cà rốt tươi, giàu vitamin A, tốt cho mắt.",
    descriptionDetail:
      "Cà rốt Đà Lạt củ to đều, màu cam sáng, giàu beta-carotene. Tốt cho thị lực và làn da.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "CQ002",
    name: "Hành tây (500g)",
    category: "củ quả",
    price: 18000,
    discount: 0,
    rating: "4/5",
    stock: 180,
    unit: "kg",
    image: "/img/poster_hanhtay.jpg",
    images: ["/img/hanhtay1.jpg", "/img/hanhtay2.jpg"],
    description: "Hành tây tươi, thơm, bổ dưỡng.",
    descriptionDetail:
      "Hành tây Đà Lạt củ chắc, thơm đặc trưng. Giàu quercetin và chất chống viêm.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "CQ003",
    name: "Khoai tây (500g)",
    category: "củ quả",
    price: 15000,
    discount: 0,
    rating: "4.5/5",
    stock: 220,
    unit: "kg",
    image: "/img/poster_khoaitay.jpg",
    images: ["/img/khoaitay1.jpg", "/img/khoaitay2.jpg"],
    description: "Khoai tây giàu tinh bột, thơm ngon.",
    descriptionDetail:
      "Khoai tây Đà Lạt củ vàng đều, chất lượng cao. Giàu tinh bột và vitamin C.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "CQ004",
    name: "Củ dền đỏ (500g)",
    category: "củ quả",
    price: 24000,
    discount: 0.15,
    rating: "4/5",
    stock: 95,
    unit: "kg",
    image: "/img/poster_cuden.jpg",
    images: ["/img/cuden1.jpg", "/img/cuden2.jpg"],
    description: "Củ dền đỏ giàu nitrate tự nhiên, tốt cho tim mạch.",
    descriptionDetail:
      "Củ dền đỏ Đà Lạt màu đỏ tươi, giàu nitrate và chất chống oxi hóa. Giúp hạ huyết áp.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "CQ005",
    name: "Su hào (1 củ)",
    category: "củ quả",
    price: 20000,
    discount: 0.1,
    rating: "4/5",
    stock: 130,
    unit: "củ",
    image: "/img/poster_suhao.jpg",
    images: ["/img/suhao1.jpg", "/img/suhao2.jpg"],
    description: "Su hào giòn ngọt, giàu chất xơ.",
    descriptionDetail:
      "Su hào Đà Lạt củ to tròn, giòn ngọt tự nhiên. Thích hợp làm salad hoặc canh.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "CQ006",
    name: "Củ cải trắng (1 củ)",
    category: "củ quả",
    price: 16000,
    discount: 0.2,
    rating: "4/5",
    stock: 150,
    unit: "củ",
    image: "/img/poster_cucai.jpg",
    images: ["/img/cucai1.jpg", "/img/cucai2.jpg"],
    description: "Củ cải trắng giòn ngọt, tốt cho tiêu hóa.",
    descriptionDetail:
      "Củ cải trắng Đà Lạt giòn ngọt, giàu enzyme tiêu hóa. Tốt cho dạ dày.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "CQ007",
    name: "Khoai lang tím (500g)",
    category: "củ quả",
    price: 19000,
    discount: 0.15,
    rating: "4.5/5",
    stock: 140,
    unit: "kg",
    image: "/img/poster_khoailang.jpg",
    images: ["/img/khoailang1.jpg", "/img/khoailang2.jpg"],
    description: "Khoai lang tím giàu anthocyanin.",
    descriptionDetail:
      "Khoai lang tím Đà Lạt ngọt bùi, giàu anthocyanin và chất xơ. Tốt cho sức khỏe tim mạch.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "CQ008",
    name: "Gừng tươi (300g)",
    category: "củ quả",
    price: 12000,
    discount: 0.1,
    rating: "4/5",
    stock: 175,
    unit: "kg",
    image: "/img/poster_gung.jpg",
    images: ["/img/gung1.jpg", "/img/gung2.jpg"],
    description: "Gừng tươi cay nồng, giúp ấm bụng.",
    descriptionDetail:
      "Gừng tươi chất lượng cao, cay thơm đặc trưng. Giúp tiêu hóa và chống viêm.",
    origin: "Cao Bằng",
    inStock: true,
    featured: false,
  },
  {
    id: "CQ009",
    name: "Tỏi tươi (500g)",
    category: "củ quả",
    price: 35000,
    discount: 0.1,
    rating: "4.5/5",
    stock: 160,
    unit: "kg",
    image: "/img/poster_toi.jpg",
    images: ["/img/toi1.jpg", "/img/toi2.jpg"],
    description: "Tỏi tươi cay thơm, giàu allicin.",
    descriptionDetail:
      "Tỏi tươi Lý Sơn củ to, múi đều, giàu allicin. Tốt cho tim mạch và miễn dịch.",
    origin: "Lý Sơn",
    certifications: ["OCOP 4 sao"],
    inStock: true,
    featured: true,
  },
  {
    id: "CQ010",
    name: "Cần tây (500g)",
    category: "củ quả",
    price: 26000,
    discount: 0.15,
    rating: "4/5",
    stock: 100,
    unit: "kg",
    image: "/img/poster_cantay.jpg",
    images: ["/img/cantay1.jpg", "/img/cantay2.jpg"],
    description: "Cần tây giòn ngọt, giàu vitamin K.",
    descriptionDetail:
      "Cần tây Đà Lạt giòn ngọt, thơm nhẹ. Giàu vitamin K và chất chống viêm.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },

  // NẤM (8 sản phẩm)
  {
    id: "N001",
    name: "Nấm đùi gà (200g)",
    category: "nấm",
    price: 31000,
    discount: 0.2,
    rating: "5/5",
    stock: 100,
    unit: "hộp",
    image: "/img/poster_namduiga.jpg",
    images: ["/img/namduiga1.jpg", "/img/namduiga2.jpg"],
    description: "Nấm đùi gà tươi, giàu dinh dưỡng.",
    descriptionDetail:
      "Nấm đùi gà Đà Lạt tươi ngon, giàu protein và chất xơ. Vị ngọt thanh tự nhiên.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "N002",
    name: "Nấm linh chi đỏ (150g)",
    category: "nấm",
    price: 33000,
    discount: 0,
    rating: "5/5",
    stock: 80,
    unit: "hộp",
    image: "/img/poster_linhchi.jpg",
    images: ["/img/linhchi1.jpg", "/img/linhchi2.jpg"],
    description: "Nấm linh chi đỏ tốt cho sức khỏe.",
    descriptionDetail:
      "Nấm linh chi đỏ Đà Lạt chất lượng cao, giàu polysaccharides. Tốt cho gan và miễn dịch.",
    origin: "Đà Lạt",
    certifications: ["OCOP 4 sao"],
    inStock: true,
    featured: true,
  },
  {
    id: "N003",
    name: "Nấm bào ngư (300g)",
    category: "nấm",
    price: 28000,
    discount: 0.15,
    rating: "4.5/5",
    stock: 120,
    unit: "hộp",
    image: "/img/poster_baongu.jpg",
    images: ["/img/baongu1.jpg", "/img/baongu2.jpg"],
    description: "Nấm bào ngư tươi, thịt dày mềm.",
    descriptionDetail:
      "Nấm bào ngư Đà Lạt thịt dày, vị ngọt thanh. Giàu protein và vitamin D.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: false,
  },
  {
    id: "N004",
    name: "Nấm mèo (200g)",
    category: "nấm",
    price: 25000,
    discount: 0.1,
    rating: "4/5",
    stock: 90,
    unit: "hộp",
    image: "/img/poster_nammeo.jpg",
    images: ["/img/nammeo1.jpg", "/img/nammeo2.jpg"],
    description: "Nấm mèo giòn giàu chất xơ.",
    descriptionDetail:
      "Nấm mèo Đà Lạt giòn dai, giàu chất xơ. Thích hợp nấu lẩu hoặc xào.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "N005",
    name: "Nấm kim châm (200g)",
    category: "nấm",
    price: 22000,
    discount: 0.2,
    rating: "4.5/5",
    stock: 130,
    unit: "gói",
    image: "/img/poster_kimcham.jpg",
    images: ["/img/kimcham1.jpg", "/img/kimcham2.jpg"],
    description: "Nấm kim châm giòn ngọt.",
    descriptionDetail:
      "Nấm kim châm Đà Lạt sạch, giòn ngọt. Thích hợp nấu lẩu hoặc nướng.",
    origin: "Đà Lạt",
    inStock: true,
    featured: false,
  },
  {
    id: "N006",
    name: "Nấm hương khô (100g)",
    category: "nấm",
    price: 45000,
    discount: 0.1,
    rating: "5/5",
    stock: 70,
    unit: "gói",
    image: "/img/poster_namhuong.jpg",
    images: ["/img/namhuong1.jpg", "/img/namhuong2.jpg"],
    description: "Nấm hương khô thơm nồng.",
    descriptionDetail:
      "Nấm hương khô chất lượng cao, thơm nức mùi. Giàu vitamin D và khoáng chất.",
    origin: "Trung Quốc",
    inStock: true,
    featured: true,
  },
  {
    id: "N007",
    name: "Nấm đông cô tươi (250g)",
    category: "nấm",
    price: 38000,
    discount: 0.15,
    rating: "5/5",
    stock: 85,
    unit: "hộp",
    image: "/img/poster_dongco.jpg",
    images: ["/img/dongco1.jpg", "/img/dongco2.jpg"],
    description: "Nấm đông cô tươi cao cấp.",
    descriptionDetail:
      "Nấm đông cô Đà Lạt tươi ngon, giàu vitamin D và chất chống ung thư.",
    origin: "Đà Lạt",
    certifications: ["VietGAP"],
    inStock: true,
    featured: true,
  },
  {
    id: "N008",
    name: "Nấm dâu rừng (200g)",
    category: "nấm",
    price: 42000,
    discount: 0.1,
    rating: "4.5/5",
    stock: 60,
    unit: "hộp",
    image: "/img/poster_daurung.jpg",
    images: ["/img/daurung1.jpg", "/img/daurung2.jpg"],
    description: "Nấm dâu rừng thơm ngon hiếm có.",
    descriptionDetail:
      "Nấm dâu rừng Đà Lạt thơm đặc trưng, giàu dinh dưỡng. Nấm cao cấp hiếm.",
    origin: "Đà Lạt",
    inStock: true,
    featured: true,
  },
];

async function seedProducts() {
  try {
    console.log("🔌 Đang kết nối MongoDB...");
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Đã kết nối MongoDB");

    console.log("🗑️  Đang xóa sản phẩm cũ...");
    await Product.deleteMany({});
    console.log("✅ Đã xóa dữ liệu cũ");

    console.log("📦 Đang nhập sản phẩm...");
    const createdProducts = await Product.insertMany(products);
    console.log(`✅ Đã nhập ${createdProducts.length} sản phẩm`);

    // Thống kê
    const stats = await Product.aggregate([
      {
        $group: {
          _id: "$category",
          count: { $sum: 1 },
        },
      },
    ]);

    console.log("\n📊 Thống kê theo danh mục:");
    stats.forEach((stat) => {
      console.log(`   - ${stat._id}: ${stat.count} sản phẩm`);
    });

    console.log("\n🎉 HOÀN THÀNH!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Lỗi:", error);
    process.exit(1);
  }
}

seedProducts();
